version: "3"

services:
  db:
    image: mysql:8.0
    environment:
        - MYSQL_ROOT_PASSWORD=12345
        - MYSQL_DATABASE=revel_db
  web:
    build: .
    ports:
        - 9001:9001
    depends_on:
        - db